# Generated by Django 4.2.18 on 2025-03-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scheduleitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
