# Generated by Django 4.2.18 on 2025-03-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_scheduleitem_options_scheduleitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='order',
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
